name: CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['*']

jobs:

    tests:
        name: Tests - PHP ${{ matrix.php }} ${{ matrix.dependency-version }}
        runs-on: ubuntu-latest
        timeout-minutes: 15
        strategy:
            matrix:
                php: [ '8.2', '8.3', '8.4', '8.5' ]
                dependency-version: [ '' ]
                include:
                    # Also tests Monolog 2
                    -   php: '8.2'
                        dependency-version: '--prefer-lowest'
        steps:
            -   uses: actions/checkout@v7
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none
            -   name: Cache Composer dependencies
                uses: actions/cache@v6
                with:
                    path: ~/.composer/cache
                    key: php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
                    restore-keys: php-${{ matrix.php }}-composer-
            -   name: Install PHP dependencies
                run: composer update ${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-progress
            -   name: PHPUnit
                run: vendor/bin/phpunit

    cs:
        name: Coding standards
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v7
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.5'
                    coverage: none
            -   name: Cache Composer dependencies
                uses: actions/cache@v6
                with:
                    path: ~/.composer/cache
                    key: php-composer-${{ hashFiles('composer.json') }}
                    restore-keys: php-composer-
            -   name: Install PHP dependencies
                run: composer install --no-interaction --no-progress
            -   name: PHP CodeSniffer
                run: vendor/bin/phpcs
            -   name: PHPStan
                run: vendor/bin/phpstan
